language: cpp
compiler:
- gcc
- clang
script:
- make hybrid-Lambda
- make unit_tests
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libcppunit-dev valgrind libboost-all-dev
before_script:
- ./bootstrap
os:
  - linux
  - osx
