language: cpp
compiler:
- gcc
- clang
script:
- make hybrid-Lambda
- make unit_tests
- cd src
- make
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq git-core libcppunit-dev libboost-all-dev graphviz
#- git submodule update --init --recursive
before_script:
- ./bootstrap
os:
  - linux
  - osx
