language: cpp
compiler:
- gcc
- clang
script:
- make hybrid-Lambda
- make check
- tests/checkbinary.sh 
- tests/fst/compute_fst.sh
- cd src
- make
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq git-core libcppunit-dev graphviz valgrind
#- git submodule update --init --recursive
before_script:
#- ./tests/checkbootstrap.sh
- ./bootstrap
os:
  - linux
  - osx
