language: cpp
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages: git-core libcppunit-dev graphviz valgrind r-base-core texlive-latex-extra texlive-fonts-recommended doxygen
  homebrew:
    packages:
    - llvm
    - cppunit
    - zlib
    update: true

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; sudo apt-get install -qq git-core libcppunit-dev graphviz valgrind r-base-core texlive-latex-extra texlive-fonts-recommended doxygen; fi
  #- if [ $TRAVIS_OS_NAME == osx ]; then rvm get 1.29.3; brew update; brew doctor; rvm install 2.3.3; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install llvm cppunit zlib ; fi

before_script:
  - ./bootstrap

script:
  - make hybrid-Lambda
  - make check
  - if [ $TRAVIS_OS_NAME == linux ]; then tests/checkbinary.sh; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then tests/fst/compute_fst.sh; fi
  #- if [ $TRAVIS_OS_NAME == linux ]; then tests/fst/compute_fst_psi.sh; fi
  - cd src; make
  - rm -r *
  - wget --no-check-certificate https://github.com/hybridLambda/hybrid-Lambda/archive/dev.tar.gz -o /dev/null
  - tar -xf dev.tar.gz
  - mv hybrid-Lambda-dev/* .
  - ./bootstrap
  - make hybrid-Lambda
  - make check
  - if [ $TRAVIS_OS_NAME == linux ]; then tests/checkbinary.sh; fi
  #- if [ $TRAVIS_OS_NAME == linux ]; then tests/fst/compute_fst.sh; fi
  - cd src; make
