language: cpp
compiler:
- gcc
- clang
script:
- make hybrid-Lambda
- make unit_tests
- ./tests/test_binaries.sh
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libcppunit-dev valgrind libboost-all-dev
before_script:
- CXXFLAGS='-O3' ./bootstrap
os:
  - linux
  - osx
