language: cpp

compiler:
- gcc
- clang

before_install:
  -os: linux
      - sudo apt-get update -qq
      - sudo apt-get install -qq git-core libcppunit-dev graphviz valgrind r-base-core
#- git submodule update --init --recursive
  -os: osx
      - sudo brew install cppunit graphviz valgrind r-base-core
      
before_script:
- ./bootstrap

script:
- make hybrid-Lambda
- make check
- tests/checkbinary.sh 
- tests/fst/compute_fst.sh
- cd src
- make

os:
- linux
- osx
osx_image: xcode61
