language: cpp
os:
  - linux
  - osx

compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; sudo apt-get install -qq git-core libcppunit-dev graphviz valgrind r-base-core; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm cppunit graphviz valgrind && brew link --force llvm; fi
before_script:
  - ./bootstrap

script:
  - make hybrid-Lambda
  - make check
  - if [ $TRAVIS_OS_NAME == linux ]; then tests/checkbinary.sh ; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then tests/fst/compute_fst.sh; fi
  - cd src; make
  - rm -r *
  - wget --no-check-certificate https://github.com/hybridLambda/hybrid-Lambda/archive/release.tar.gz -o /dev/null
  - tar -xf release.tar.gz
  - mv hybrid-Lambda-release/* .
  - ./bootstrap
  - make hybrid-Lambda
  - make check
  - if [ $TRAVIS_OS_NAME == linux ]; then tests/checkbinary.sh ; fi
  #- if [ $TRAVIS_OS_NAME == linux ]; then tests/fst/compute_fst.sh; fi
  - cd src; make  
